name: open-elections
version: '0.1.0.0'
synopsis: open-elections data re-processor
category: Data
author: Adam Conner-Sax
maintainer: adam_conner_sax@yahoo.com
copyright: 2019 Adam Conner-Sax
license: BSD3
github: blueripple/open-elections
extra-source-files:
- ChangeLog.md
- Readme.md

executables:
  AggregateBySLD:
    main: AggregateBySLD.hs
    source-dirs: app
    dependencies:
      - base
      - bytestring
      - cassava
      - containers
      - directory
      - foldl
      - fuzzyset
      - map-reduce-folds
      - streamly >= 0.7
      - text
      - vector
      
